### ISSUE TITLE
Stored Procedures and Function

### ISSUE THREAD

**Issue by anderson-0** [rahmanfadhil/cotton#9]
I did not saw it in the documentation so I am not sure this is already in place.
How would you execute a stored procedure or function?

**Comment by rahmanfadhil** [comment]
You can't build a stored procedure programmatically at the moment. However, you still can create and execute a stored procedure manually via the `query` method provided by the database connection.

Example:

```ts
const result = await db.query("EXEC procedure_name;")
```

Personally, I never saw anybody using stored procedure via an ORM, since the ORM itself already provides a very easy way to execute complex queries over and over again. 🤔
